#!/bin/env bash
#
# Obfuscate by @CesarHackGray
# Creditos para @CesarHackGray
# Servicio de ayuda https://t.me/CesarGray
# Channel: https://www.youtube.com/channel/UCjs0N8PbEo-se0r_4O_svNQ
#
#
z="
";wz='__ \';Iz='B='\''\';Rz='='\''\0';Hz='1;33';dBz='rHac';Bz='033[';VBz=' \/ ';az=')';WBz='\/ "';UBz='  \/';nz='_| _';Nz='1;36';ZBz='Crea';OBz='_  >';tz=' \  ';fz='_   ';Tz='2m'\''';Pz='1;37';Sz='33[3';SBz='\/\_';xz='_/ _';RBz=' "  ';GBz='___|';Ez='G='\''\';Vz='tf "';Oz='W='\''\';Gz='Y='\''\';yz='__\ ';sz='/   ';CBz='/ __';lz=' ___';cz='___ ';Cz='1;31';cBz='Cesa';XBz=' -e ';jz=' " |';JBz=' /_/';LBz='__| ';HBz='\  _';Kz='M='\''\';Yz=' $(c';fBz='y"';IBz='__//';bz=' " .';Dz='m'\''';DBz=' | "';BBz='_ \ ';Zz='lear';vz=' |/ ';hz='   .';rz=' _/"';pz='___/';PBz=' \__';Fz='1;32';Uz='prin';mz='  |_';EBz='  \ ';Az='R='\''\';Jz='1;34';YBz='$W" ';eBz='kGra';oz='  __';Lz='1;35';iz='___"';Qz='Gren';aBz='ted ';dz='    ';TBz='_|  ';Wz='$G"';Mz='C='\''\';ez='   _';kz='   |';KBz='  /\';Xz='echo';QBz='____';bBz='by @';FBz='\  \';MBz=' |\_';qz=' __|';ABz='\/ _';gz='__  ';uz='  | ';NBz='>\__';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Bz$Pz$Dz$z$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$z$Xz$Yz$Zz$az$z$Xz$bz$cz$dz$dz$ez$fz$dz$dz$dz$gz$dz$dz$hz$iz$z$Xz$jz$kz$lz$fz$mz$nz$cz$oz$pz$mz$oz$gz$qz$rz$z$Xz$jz$kz$sz$tz$uz$vz$wz$xz$yz$oz$ABz$BBz$CBz$DBz$z$Xz$jz$kz$kz$EBz$uz$tz$pz$FBz$GBz$uz$HBz$IBz$JBz$DBz$z$Xz$jz$GBz$GBz$KBz$LBz$MBz$gz$NBz$OBz$LBz$PBz$OBz$QBz$DBz$z$Xz$RBz$dz$dz$SBz$QBz$TBz$UBz$dz$VBz$dz$dz$VBz$dz$WBz$z$Xz$XBz$YBz$dz$dz$dz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz"
